name: setup-pnpm
description: Setup Node.js, pnpm, and install dependencies.

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json

    - name: Setup pnpm
      uses: pnpm/action-setup@v6
      with:
        package_json_file: package.json
        run_install: false

    - name: Setup pnpm cache and registry
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: pnpm
        registry-url: https://npm.pkg.github.com
        scope: "@adamaho"

    - name: Install dependencies
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: pnpm install --frozen-lockfile
