name: setup-pnpm
description: Setup Node.js, pnpm, and install dependencies.

runs:
  using: composite
  steps:
    - name: Configure pnpm authentication
      shell: bash
      run: echo "PNPM_CONFIG_NPMRC_AUTH_FILE=$GITHUB_WORKSPACE/.npmrc" >> "$GITHUB_ENV"

    - name: Setup pnpm, Node.js, cache, and dependencies
      uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
      with:
        version: 12.3.4
        runtime: node@24.15.0
        cache: true
        cache-dependency-path: pnpm-lock.yaml
        require-lockfile: true
